import type { TextStyle, ViewStyle } from 'react-native';

export const createTextStyle = <T extends TextStyle>(props: T): object => {
  return {
    color: props.color,
    fontFamily: props.fontFamily,
    fontSize: props.fontSize,
    fontWeight: props.fontWeight,
    fontStyle: props.fontStyle,
    letterSpacing: props.letterSpacing,
    lineHeight: props.lineHeight,
    textAlign: props.textAlign,
    textDecorationLine: props.textDecorationLine,
    textTransform: props.textTransform,
    textShadowColor: props.textShadowColor,
    textShadowOffset: props.textShadowOffset,
    textShadowRadius: props.textShadowRadius,
    textAlignVertical: props.textAlignVertical,
    textDecorationColor: props.textDecorationColor,
    textDecorationStyle: props.textDecorationStyle,
    userSelect: props.userSelect,
  };
};

export const createViewStyle = <T extends ViewStyle>(props: T): object => {
  return {
    backgroundColor: props.backgroundColor,
    borderColor: props.borderColor,
    borderWidth: props.borderWidth,
    borderRadius: props.borderRadius,
    padding: props.padding,
    margin: props.margin,
    flexDirection: props.flexDirection,
    justifyContent: props.justifyContent,
    alignItems: props.alignItems,
    position: props.position,
    top: props.top,
    bottom: props.bottom,
    left: props.left,
    right: props.right,
    width: props.width,
    height: props.height,
    maxWidth: props.maxWidth,
    maxHeight: props.maxHeight,
    minWidth: props.minWidth,
    minHeight: props.minHeight,
    overflow: props.overflow,
    shadowColor: props.shadowColor,
    shadowOffset: props.shadowOffset,
    shadowOpacity: props.shadowOpacity,
    shadowRadius: props.shadowRadius,
    elevation: props.elevation,
    zIndex: props.zIndex,
    opacity: props.opacity,
    transform: props.transform,
    borderTopWidth: props.borderTopWidth,
    borderBottomWidth: props.borderBottomWidth,
    borderLeftWidth: props.borderLeftWidth,
    borderRightWidth: props.borderRightWidth,
    borderTopColor: props.borderTopColor,
    borderBottomColor: props.borderBottomColor,
    borderLeftColor: props.borderLeftColor,
    borderRightColor: props.borderRightColor,
    borderStyle: props.borderStyle,
  };
};
